spring: 
  profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dev
---
spring:
  profiles: text
  application:
    name: microservicecloud-config-text

 

